### ISSUE TITLE
Teensy LC/3.2

### ISSUE THREAD

**Issue by raenji-sk** [tonton81/TSPISlave#1]
Hi did you test it with LC?
I am just testing your sketch from the example file.
When I select Teensy 3.6 in IDE 1.8.8 it compiles OK, but for 3.2 and LC I get an error
`C:\Users\Andrej\Documents\teensylc-tspislave-fastled\teensylc-tspislave-fastled.ino:11:29: error: 'SPI2' was not declared in this scope

 TSPISlave mySPI = TSPISlave(SPI2, miso, mosi, sck, cs, spimode);

                             ^

Error compiling for board Teensy LC.`

Tried to change the pins and SPI[x] to different values, but no effect.

Andrej

**Comment by raenji-sk** [comment]
Just an update, when setting pins to 11-14 and SPI[x] to SPI, I get the following error:
`C:\Users\Andrej\Documents\Arduino\libraries\TSPISlave-master\TSPISlave.cpp: In member function 'bool TSPISlave::setSlaveSCK(uint8_t)':

C:\Users\Andrej\Documents\Arduino\libraries\TSPISlave-master\TSPISlave.cpp:199:5: error: 'CORE_PIN32_CONFIG' was not declared in this scope

     CORE_PIN32_CONFIG = PORT_PCR_MUX(2);

     ^

Error compiling for board Teensy LC.`

**Comment by tonton81** [comment]
yeah theres one ifdef i forgot to add but it does work on T3.2/LC, i’ll try to patch it tomorrow, this is because i worked on SPI1/2 after the 3.2/LC was tested

**Comment by raenji-sk** [comment]
OK, thanks. I will test it next week if I have some time.

**Comment by tonton81** [comment]
just updated the library to support parallel running of TSPISlave.h and and SPI.h, in case the user who has more than 1 SPI interface can use both master and slave modes together.

Also defined the pins for T3.5 / T3.6 to not cause compile error when compiling for Teensy 3.2/LC

Also keep in mind the SPI interface of LC is max 6MHz and does not mean it will work that far, results have tested around 4-5MHz should be fine. The SPI1 interface on LC can run at 12MHz slave mode, 11MHz was tested in the past

**Comment by raenji-sk** [comment]
Thanks, compiles OK for both 3.2 and LC.
